name: build

on:
  push:
    branches:
      - 'master'
    tags:
      - '*'
    paths-ignore:
      - '**.md'
  pull_request:
    branches:
      - 'master'
    paths-ignore:
      - '**.md'
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  prep:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.prepare.outputs.version }}
      build_date: ${{ steps.prepare.outputs.date }}
    steps:
      -
        name: Prepare
        id: prepare
        run: |
          echo version=$(git -c 'versionsort.suffix=-'     ls-remote --exit-code --refs --sort='version:refname' --tags https://github.com/cloudflare/cloudflared '*.*.*'     | tail --lines=1     | cut --delimiter='/' --fields=3) >> $GITHUB_OUTPUT
          echo date=$(date -u +'%Y-%m-%dT%H:%M:%SZ')

  build:
    runs-on: ubuntu-latest
    needs: prep
    env:
      DOCKER_USERNAME: buildsocietybot
      DOCKER_IMAGE: buildsociety/cloudflared
      DOCKER_PLATFORMS: linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64,linux/386,linux/ppc64le,linux/s390x
    strategy:
      fail-fast: false
#      matrix:
#        platforms:
#          - linux/amd64
#          - linux/arm/v6
#          - linux/arm/v7
#          - linux/arm64
#          - linux/386
#          - linux/ppc64le
#          - linux/s390x
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Checkout Cloudflared
        uses: actions/checkout@v3
        with:
          repository: 'cloudflare/cloudflared'
          path: 'cloudflared'
          ref: ${{ needs.prep.outputs.version }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile
          #platforms: ${{ matrix.platforms }}
          platforms: ${{ env.DOCKER_PLATFORMS }}
          push: true
          tags: |
            buildsociety/cloudflared:latest
            buildsociety/cloudflared:${{ needs.prep.outputs.version }}
            ghcr.io/buildsociety/cloudflared:latest
            ghcr.io/buildsociety/cloudflared:${{ needs.prep.outputs.version }}
          build-args: |
            VERSION=${{ needs.prep.outputs.version }}
            BUILD_DATE=${{ needs.prep.outputs.build_date }}
            VCS_REF=${GITHUB_SHA::8}
